import { expect, test, type Page } from '@playwright/test';
const token = 'isolated-browser-test-token';
const workspace = {id:'workspace-test',title:'浏览器隔离测试课题',description:'仅用于测试的本地资料',links:[],created_at:'2026-10-01',updated_at:'2026-10-01'};
const tools = ['overview','search','details','check','compare','prepare','recommend','read_project','papers_search','papers_details','papers_download','papers_read','papers_notes','papers_import','papers_list','writing_prepare','writing_create','writing_search','writing_assess','writing_get','writing_list','writing_materials','writing_draft','writing_export','loop_get','loop_control','loop_prepare_review','loop_submit_review','loop_step','loop_feedback','planning_prepare','planning_create','planning_get','planning_list','planning_save','planning_task','planning_evidence','planning_export','journal_sources','journal_build','journal_import','journal_refresh','journal_peers','submission_track','documents_standards','documents_audit','documents_normalize','documents_generate','documents_language_check','word_status','word_targets','word_select','word_selection','word_insert','word_replace','word_comment','word_track','word_table','word_style'].map(name => ({name,description:'浏览器测试能力：' + name,category:'test',available:!name.startsWith('word_'),unavailable_reason:name.startsWith('word_') ? '隔离浏览器没有 Windows COM' : '',network:['papers_search','writing_search'].includes(name),desktop:name.startsWith('word_'),mutates:false,approval_required:false,input_schema:{type:'object',properties:name === 'papers_search' ? {query:{type:'string',minLength:1},limit:{type:'integer',default:10}} : name === 'documents_language_check' ? {text:{type:'string',minLength:1}} : {},required:name === 'papers_search' ? ['query'] : []}}));
async function mockBackend(page:Page) {
  const calls:{url:string;method:string;body:any}[] = [];
  let currentWorkspace = {...workspace};let sessions:any[] = [];let currentRun:any;let messages:any[] = [];
  await page.route('**/api/**',async route => {
    const request = route.request();const url = new URL(request.url());const method = request.method();let body:any = undefined;try{body=request.postDataJSON();}catch{}
    calls.push({url:url.pathname,method,body});
    if(request.headers()['x-paperflow-token'] !== token){await route.fulfill({status:403,json:{status:'error',error_code:'AUTH_REQUIRED',message:'使用启动链接重新进入',data:null}});return;}
    let data:any = {};
    if(url.pathname === '/api/workbench/capabilities')data={tools,local_only:true};
    else if(url.pathname === '/api/workbench/workspaces'){if(method === 'POST'){currentWorkspace={...workspace,...body,id:'workspace-created'};data=currentWorkspace;}else data=[currentWorkspace];}
    else if(url.pathname === '/api/model/status')data={configured:true,provider:'openai_compatible',base_url:'https://model.test/v1',model:'test-tool-model',consented:true};
    else if(url.pathname === '/api/model/config' || url.pathname === '/api/model/consent')data={configured:true};
    else if(url.pathname === '/api/model/test')data={connected:true,usage:{input_tokens:3,output_tokens:1}};
    else if(url.pathname === '/api/workbench/assets' || url.pathname === '/api/workbench/artifacts')data=[];
    else if(url.pathname === '/api/workbench/action'){
      if(['planning_list','writing_list','papers_list','search'].includes(body.action))data=[];
      else if(body.action === 'papers_search')data={papers:[{paper_id:'paper-test',title:'<img src=x onerror="window.hacked=true">真实文本安全测试',authors:['测试作者'],source_id:'crossref',year:2026,abstract:'仅测试夹具'}],source_statuses:[{source_id:'crossref',status:'success'}]};
      else if(body.action === 'papers_details')data={paper:{paper_id:'paper-test',title:'仅测试文献',abstract:'测试摘要'},acquisition:{status:'unavailable',reason:'测试未下载全文'}};
      else data={message:'本地浏览器测试响应'};
    }
    else if(url.pathname === '/api/agent/sessions'){if(method === 'POST'){data={id:'session-test',workspace_id:body.workspace_id,title:body.title};sessions=[data];}else data=sessions;}
    else if(url.pathname.endsWith('/messages')){
      messages=[{role:'user',text:body.message}];currentRun={id:'run-test',session_id:'session-test',workspace_id:workspace.id,status:'awaiting_approval',budget:body.budget,usage:{model_calls:1,tool_calls:0,input_tokens:null,output_tokens:null},pending_approval:{approval_id:'approval-test',tool_name:'documents_generate',arguments:{title:'测试草稿'},reason:'需批准生成新副本'}};data=currentRun;
    }
    else if(url.pathname === '/api/agent/sessions/session-test')data={...sessions[0],messages,runs:currentRun ? [currentRun] : []};
    else if(url.pathname.endsWith('/events')){
      const events=[{seq:1,type:'tool_started',data:{call_id:'call-test',tool_name:'papers_list',arguments:{limit:20}}},{seq:2,type:'tool_result',data:{call_id:'call-test',tool_name:'papers_list',ok:true,result:{papers:[]}}},{seq:3,type:'approval_required',data:currentRun?.pending_approval || {}},{seq:4,type:'reasoning',data:{text:'不应展示的隐藏思维链'}}];
      await route.fulfill({status:200,contentType:'text/event-stream',body:events.filter(e => e.seq > Number(url.searchParams.get('after') || 0)).map(e => 'data: ' + JSON.stringify(e) + '\n\n').join('')});return;
    }
    else if(url.pathname.endsWith('/approve')){currentRun={...currentRun,status:body.approved ? 'completed' : 'cancelled',pending_approval:null};messages.push({role:'assistant',text:'已完成实际测试工具执行摘要。'});data=currentRun;}
    else if(url.pathname.endsWith('/cancel')){currentRun={...currentRun,status:'cancelled',pending_approval:null};data=currentRun;}
    else if(url.pathname === '/api/agent/runs/run-test')data=currentRun;
    await route.fulfill({status:200,json:{status:'success',data}});
  });
  return calls;
}
test('启动认证、现代导航与所有业务页面可打开',async ({page}) => {
  const calls=await mockBackend(page);await page.goto('/app/?token=' + token + '#/home');await expect(page.getByRole('heading',{name:'浏览器隔离测试课题，从这里继续'})).toBeVisible();expect(page.url()).not.toContain('?token=');expect(await page.evaluate(() => sessionStorage.getItem('paperflow.web-token'))).toBe(token);
  const pages=[['科研规划','科研规划'],['文献库','文献库'],['文献写作','文献支持写作'],['选刊与数据源','选刊与数据源'],['投稿与参考文献','投稿与参考文献'],['文档与格式','文档与格式'],['任务与成果','任务与成果'],['设置与 MCP 接入','设置与接入']];
  for(const [link,heading] of pages){await page.getByRole('navigation',{name:'主导航'}).getByRole('link',{name:link,exact:true}).click();await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible();}
  expect(calls.some(call => call.url.includes('search_reviews'))).toBe(false);expect(await page.locator('iframe').count()).toBe(0);
});
test('新建工作区与真实空状态，不插入生产假成果',async ({page}) => {await mockBackend(page);await page.goto('/app/?token=' + token + '#/home');await page.getByLabel('工作区名称').fill('新建真实API工作区');await page.getByLabel('研究方向 / 说明').fill('浏览器测试中的用户材料');await page.getByRole('button',{name:'创建工作区',exact:true}).click();await expect(page.getByRole('heading',{name:'新建真实API工作区，从这里继续'})).toBeVisible();await page.getByRole('navigation').getByRole('link',{name:'任务与成果',exact:true}).click();await expect(page.getByRole('heading',{name:'尚无真实成果文件'})).toBeVisible();});
test('Agent幂等发送、实际工具卡、审批和隐藏推理屏蔽',async ({page}) => {const calls=await mockBackend(page);await page.goto('/app/?token=' + token + '#/agent');await page.getByLabel('Agent 消息').fill('检查我的研究证据并生成草稿');await expect(page.getByRole('button',{name:'开始执行'})).toBeDisabled();await page.getByLabel('授权本次消息与工作区结果发送模型').check();await page.getByRole('button',{name:'开始执行'}).click();await expect(page.getByText('这一步需要你的批准')).toBeVisible();await expect(page.locator('.execution-card').filter({hasText:'papers_list'})).toBeVisible();await expect(page.getByText('不应展示的隐藏思维链')).toHaveCount(0);await expect(page.getByText('未知').first()).toBeVisible();await page.getByRole('button',{name:'核对参数并批准'}).click();await expect(page.getByText('已完成实际测试工具执行摘要。')).toBeVisible();const send=calls.filter(call => call.url.endsWith('/messages'));expect(send).toHaveLength(1);expect(send[0].body).toMatchObject({allow_network:false,allow_writes:false,consent:true,budget:{model_calls:40,tool_calls:80,seconds:1800}});expect(send[0].body.request_id).toBeTruthy();expect(calls.find(call => call.url.endsWith('/approve'))?.body).toEqual({approval_id:'approval-test',approved:true});});
test('模型Key不回显和不持久化，MCP模式不执行本地Agent',async ({page}) => {const calls=await mockBackend(page);await page.goto('/app/?token=' + token + '#/settings');await page.getByLabel('API Key').fill('private-key-browser-test');await page.getByRole('button',{name:'保存模型配置'}).click();await expect(page.getByLabel('API Key')).toHaveValue('');expect(await page.evaluate(() => JSON.stringify({...localStorage,...sessionStorage}))).not.toContain('private-key-browser-test');expect(calls.find(call => call.url === '/api/model/config')?.body.api_key).toBe('private-key-browser-test');await page.getByLabel('执行模式').selectOption('mcp');const before=calls.filter(call => call.url.startsWith('/api/agent/')).length;await page.getByRole('navigation').getByRole('link',{name:'Agent 工作区',exact:true}).click();await expect(page.getByRole('heading',{name:'外部 MCP 执行'})).toBeVisible();await expect(page.getByText('python -m paperflow run')).toBeVisible();expect(calls.filter(call => call.url.startsWith('/api/agent/')).length).toBe(before);});
test('不可信正文安全渲染，窄屏导航没有横向溢出',async ({page}) => {await mockBackend(page);await page.goto('/app/?token=' + token + '#/papers');await page.getByRole('tab',{name:'真实检索'}).click();await page.getByLabel('检索词 / 名称').fill('测试文献');await page.getByLabel(/允许本次操作联网/).check();await page.getByRole('button',{name:'检索学术文献'}).click();await expect(page.getByRole('heading',{name:'<img src=x onerror="window.hacked=true">真实文本安全测试'})).toBeVisible();expect(await page.evaluate(() => (window as any).hacked)).toBeUndefined();expect(await page.locator('.paper-list img').count()).toBe(0);await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'展开主导航'}).click();await page.getByRole('navigation').getByRole('link',{name:'项目首页',exact:true}).click();await expect(page.getByRole('heading',{name:'浏览器隔离测试课题，从这里继续'})).toBeVisible();expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);});
test('没有启动令牌时不请求或显示私有项目',async ({page}) => {const calls=await mockBackend(page);await page.goto('/app/#/home');await expect(page.getByRole('heading',{name:'请使用启动链接进入'})).toBeVisible();expect(calls).toHaveLength(0);});
