import { beforeEach, describe, expect, it, vi } from 'vitest';
import { action, api, authHeaders, errorText, initializeToken, post, records, streamEvents, upload, ApiError } from '../src/api';
function response(data:unknown,status = 200){return new Response(JSON.stringify({status:'success',data}),{status,headers:{'Content-Type':'application/json'}});}
beforeEach(() => {history.replaceState({},'', '/?token=test-access#/home');initializeToken();});
describe('访问令牌与真实请求',() => {
  it('移除地址栏令牌，只持久化网页凭证到 sessionStorage',() => {expect(location.search).toBe('');expect(location.hash).toBe('#/home');expect(sessionStorage.getItem('paperflow.web-token')).toBe('test-access');expect(localStorage.length).toBe(0);expect(authHeaders().get('X-PaperFlow-Token')).toBe('test-access');});
  it('以 sessionStorage 恢复刷新身份',() => {history.replaceState({},'', '/app/#/papers');expect(initializeToken()).toBe('test-access');});
  it('每个业务操作发送认证和明确作用域，不自动重试',async () => {const fetch = vi.fn().mockResolvedValue(response({revision:2}));vi.stubGlobal('fetch',fetch);expect(await action('planning_get',{project_id:'project-test'},'workspace-test')).toEqual({revision:2});const [url,init] = fetch.mock.calls[0];expect(url).toBe('/api/workbench/action');expect(init.headers.get('X-PaperFlow-Token')).toBe('test-access');expect(JSON.parse(init.body)).toEqual({action:'planning_get',params:{project_id:'project-test'},workspace_id:'workspace-test',allow_network:false,approved:false});expect(fetch).toHaveBeenCalledTimes(1);});
  it('403 显示重新进入启动链接，不把模型Key当访问token',async () => {const event = vi.fn();window.addEventListener('paperflow:unauthorized',event);vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('{}',{status:403})));await expect(api('/api/model/status')).rejects.toThrow('启动链接');expect(event).toHaveBeenCalledTimes(1);window.removeEventListener('paperflow:unauthorized',event);});
  it('清楚保留服务的版本冲突并提示手动合并',async () => {vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({status:'error',error_code:'REVISION_CONFLICT',message:'冲突'}),{status:409})));try{await post('/api/workbench/action',{});}catch(e){expect(e).toBeInstanceOf(ApiError);expect(errorText(e)).toContain('编辑仍在此页');}});
  it('上传原始File，文件名编码并使用不透明资产标识',async () => {const fetch = vi.fn().mockResolvedValue(response({asset_id:'asset-test'}));vi.stubGlobal('fetch',fetch);const file = new File(['测试'], '研究材料.pdf',{type:'application/pdf'});await upload(file,'workspace-test');const [url,init] = fetch.mock.calls[0];expect(url).toContain('workspace_id=workspace-test');expect(init.body).toBe(file);expect(init.headers.get('X-File-Name')).toBe(encodeURIComponent(file.name));expect(init.headers.get('Content-Type')).toBe('application/pdf');});
  it('未知网络错误不会重发副作用',async () => {const fetch = vi.fn().mockRejectedValue(new TypeError('offline'));vi.stubGlobal('fetch',fetch);await expect(post('/api/agent/sessions/test/messages',{request_id:'single-request'})).rejects.toThrow('无法连接本地服务');expect(fetch).toHaveBeenCalledTimes(1);});
});
describe('鉴权事件流',() => {
  it('按游标读取SSE，忽略重复序号且不发送消息',async () => {const encoder = new TextEncoder();const stream = new ReadableStream({start(controller){controller.enqueue(encoder.encode('data: {"seq":1,"type":"status","data":{"status":"running"}}\r\n\r\ndata: {"seq":2,"type":"tool_started","data":{"tool_name":"papers_read"}}\n\n'));controller.enqueue(encoder.encode('data: {"seq":2,"type":"tool_started","data":{}}\n\ndata: {"seq":3,"type":"status","data":{"status":"completed"}}\n\n'));controller.close();}});const fetch = vi.fn().mockResolvedValue(new Response(stream,{headers:{'Content-Type':'text/event-stream'}}));vi.stubGlobal('fetch',fetch);const events:any[]=[];await streamEvents('run-test',1,new AbortController().signal,e => events.push(e));expect(events.map(e => e.seq)).toEqual([2,3]);expect(fetch.mock.calls[0][0]).toBe('/api/agent/runs/run-test/events?after=1');expect(fetch.mock.calls[0][1].headers.get('X-PaperFlow-Token')).toBe('test-access');expect(fetch.mock.calls[0][1].method).toBeUndefined();});
  it('事件流失败暴露轮询回退而不是重发messages',async () => {vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('',{status:503})));await expect(streamEvents('run-test',3,new AbortController().signal,() => {})).rejects.toThrow('状态轮询');});
});
it('兼容真实列表envelope的不同模块字段',() => {expect(records({papers:[{paper_id:'paper-test'}]})).toHaveLength(1);expect(records({assets:[{asset_id:'asset-test'}]},'assets')).toHaveLength(1);expect(records({message:'无记录'})).toEqual([]);});
