import { useState } from 'react';
import { describe, expect, it } from 'vitest';
import { fireEvent, render, screen } from '@testing-library/react';
import { initialValue, resolve, SchemaEditor, validate } from '../src/components/SchemaForm';
import type { Schema } from '../src/types';
const schema:Schema = {type:'object',required:['title','tasks'],properties:{title:{type:'string',minLength:1},tasks:{type:'array',default:[],items:{$ref:'#/$defs/Task'}},max_search_calls:{type:'integer',minimum:0,maximum:120,default:0}},$defs:{Task:{type:'object',required:['text','completion_condition'],properties:{text:{type:'string',minLength:1},completion_condition:{type:'string',minLength:1},status:{type:'string',enum:['todo','doing','done','blocked'],default:'todo'},depends_on:{type:'array',items:{type:'string'},default:[]}}}}};
describe('结构化科研表单',() => {
  it('从实际schema初始化空状态，而不是生成实验或文献',() => {expect(initialValue(schema)).toEqual({title:'',tasks:[],max_search_calls:0});expect(resolve({$ref:'#/$defs/Task'},schema).properties?.text).toEqual({type:'string',minLength:1});});
  it('允许服务支持的零检索预算并拒绝超出硬上限',() => {expect(validate(schema,{title:'真实研究',tasks:[],max_search_calls:0})).toEqual([]);expect(validate(schema,{title:'',tasks:[],max_search_calls:121})).toEqual(expect.arrayContaining(['标题至少需要 1 个字符','检索次数（可为零）不能大于 120']));});
  it('嵌套表单支持添加、编辑、移除任务，不需要手写JSON',() => {function Form(){const [value,setValue] = useState(initialValue(schema));return <><SchemaEditor schema={schema} value={value} onChange={setValue}/><output data-testid="value">{JSON.stringify(value)}</output></>;}render(<Form/>);fireEvent.change(screen.getByLabelText('标题'),{target:{value:'我的课题'}});fireEvent.click(screen.getByRole('button',{name:'添加任务'}));fireEvent.change(screen.getByLabelText('正文 / 研究材料'),{target:{value:'执行对照实验'}});fireEvent.change(screen.getByLabelText('完成条件'),{target:{value:'生成对照记录'}});fireEvent.change(screen.getByLabelText('状态'),{target:{value:'blocked'}});expect(JSON.parse(screen.getByTestId('value').textContent || '{}').tasks[0]).toEqual({text:'执行对照实验',completion_condition:'生成对照记录',status:'blocked',depends_on:[]});fireEvent.click(screen.getByRole('button',{name:'移除第 1 项'}));expect(JSON.parse(screen.getByTestId('value').textContent || '{}').tasks).toEqual([]);});
  it('初始化Pydantic默认工厂的非空值数组字段为真实空列表',() => {const section:Schema = {type:'object',required:['title'],properties:{title:{type:'string',minLength:1},paragraphs:{type:'array',items:{type:'string'},maxItems:300},tables:{type:'array',items:{type:'object',properties:{}}}}};expect(initialValue(section)).toEqual({title:'',paragraphs:[],tables:[]});});
  it('保持省略的可选字段，不错误发送null占位',() => {const optional:Schema = {type:'object',properties:{revision:{anyOf:[{type:'integer',minimum:1},{type:'null'}],default:null}}};expect(initialValue(optional)).toEqual({});});
});
