import { useState } from 'react';
import { api, errorText, post, records } from '../api';
import { useWorkbench } from '../context';
import type { Data } from '../types';
import { Badge, Button, Card, Empty, Field, Icon, Loading, Notice, PageHeading, Status } from '../components/ui';
export default function Home() {
  const {workspace,workspaces,selectWorkspace,refreshWorkspaces,loading,execute,link,askAgent,mode} = useWorkbench();
  const [title,setTitle] = useState('');const [description,setDescription] = useState('');const [busy,setBusy] = useState(false);const [error,setError] = useState('');
  const [existing,setExisting] = useState<Data[]>([]); const [kind,setKind] = useState('planning'); const [prompt,setPrompt] = useState('');
  const [runs,setRuns] = useState<Data[]>([]); const [runLoaded,setRunLoaded] = useState(false);
  async function create() {setBusy(true);setError('');try {const created = await post('/api/workbench/workspaces',{title,description});await refreshWorkspaces();selectWorkspace(created.workspace?.id || created.id);setTitle('');setDescription('');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function discover() {setError('');try {const data = await execute(kind === 'planning' ? 'planning_list' : 'writing_list',{limit:30,offset:0,discover:true});setExisting(records(data));}catch(e){setError(errorText(e));}}
  async function loadRuns() { setError('');try { const data = await api('/api/agent/sessions' + (workspace ? '?workspace_id=' + encodeURIComponent(workspace.id) : '')); const sessions = records(data); const details = await Promise.all(sessions.slice(0,8).map(session => api(`/api/agent/sessions/${encodeURIComponent(session.id)}`)));setRuns(details.flatMap(item => item.runs || []));setRunLoaded(true); } catch(e) {setError(errorText(e));} }
  return <>
    <PageHeading eyebrow="YOUR RESEARCH, CONNECTED" title={workspace ? `${workspace.title}，从这里继续` : '让研究有条不紊地向前'} description="把研究问题、文献证据与稿件放进同一个工作区。每一次推进，都留下可追溯的结果。"/>
    <section className="hero-card"><div className="hero-symbol"><Icon name="agent" size={34}/></div><div><Badge tone="violet">{mode === 'standalone' ? '独立 Agent · 受控执行' : '外部 MCP · 本地业务可用'}</Badge><h2>从一个研究问题开始</h2><p>{mode === 'standalone' ? '说清目标，选择材料，再授权 Agent 规划和执行。你始终掌握联网、写入与预算。' : '外部 Agent 通过 MCP 调用相同业务服务；网页不假称已连接外部执行器。'}</p><div className="hero-composer"><input aria-label="交给 Agent 的研究目标" placeholder="你希望推进哪一个研究问题？" value={prompt} onChange={e => setPrompt(e.target.value)}/><Button disabled={!prompt.trim() || mode === 'mcp' || !workspace} onClick={() => askAgent(prompt)}><Icon name="arrow" size={18}/>交给 Agent</Button></div>{!workspace && <small>先在下方创建或选择工作区。</small>}</div></section>
    {error && <Notice danger>{error}</Notice>}
    <div className="metric-grid">{[{label:'工作区',value:workspaces.length,note:'真实本地项目容器',icon:'folder'},{label:'关联研究',value:workspace?.links?.length || 0,note:'规划、写作与文献',icon:'planning'},{label:'运行任务',value:runLoaded ? runs.filter(r => ['running','queued','awaiting_approval'].includes(r.status)).length : '—',note:'读取会话后显示',icon:'bolt'}].map(item => <div className="metric" key={item.label}><Icon name={item.icon}/><small>{item.label}</small><strong>{item.value}</strong><span>{item.note}</span></div>)}</div>
    <div className="two-columns"><Card title="你的工作区" description="独立容器，不改写已有项目编号" action={<Badge>{workspaces.length} 个</Badge>}>
      {loading ? <Loading/> : !workspaces.length ? <Empty title="还没有工作区" text="创建第一个工作区，把研究过程与成果串起来。"/> : <div className="workspace-grid">{workspaces.map(item => <button className={`workspace-card ${item.id === workspace?.id ? 'selected' : ''}`} key={item.id} onClick={() => selectWorkspace(item.id)}><div><span className="workspace-symbol"><Icon name="folder"/></span>{item.id === workspace?.id && <Badge tone="violet">当前</Badge>}</div><h3>{item.title}</h3><p>{item.description || '尚未填写说明'}</p><small>{item.links?.length || 0} 个关联项目<Icon name="chevron" size={14}/></small></button>)}</div>}
    </Card><Card title="新建工作区" description="为一个课题保留清晰的上下文"><form onSubmit={e => {e.preventDefault();void create();}}><Field label="工作区名称"><input required maxLength={300} value={title} onChange={e => setTitle(e.target.value)} placeholder="例如：研究课题名称"/></Field><Field label="研究方向 / 说明"><textarea rows={3} maxLength={4000} value={description} onChange={e => setDescription(e.target.value)} placeholder="研究目标、范围和当前阶段"/></Field><Button type="submit" disabled={busy || !title.trim()}><Icon name="plus" size={16}/>{busy ? '创建中…' : '创建工作区'}</Button></form></Card></div>
    <div className="two-columns"><Card title="关联已有研究" description="发现原有规划和写作项目，手动归入当前工作区"><div className="inline-form"><select aria-label="关联项目类型" value={kind} onChange={e => {setKind(e.target.value);setExisting([]);}}><option value="planning">科研规划</option><option value="writing">文献写作</option></select><Button variant="secondary" onClick={() => void discover()}>发现本地项目</Button></div>{!existing.length ? <Empty title="尚未发现项目" text="已有项目保持原编号，关联不会迁移或覆盖数据。"/> : existing.map(item => <div className="list-row" key={item.project_id}><div><strong>{item.title || item.profile?.title || item.project_id}</strong><small>{item.project_id} · 版本 {item.revision}</small></div><Button variant="secondary" disabled={!workspace || workspace.links?.some(l => l.target_id === item.project_id)} onClick={async () => {try {await link(kind,item.project_id);}catch(e){setError(errorText(e));}}}>关联</Button></div>)}</Card>
    <Card title="运行中的任务" description="真实会话任务与需要你处理的审批" action={<Button variant="ghost" onClick={() => void loadRuns()}><Icon name="refresh" size={16}/>读取任务</Button>}>{!runLoaded ? <Empty title="尚未读取运行记录" text="读取当前工作区的 Agent 会话，查看执行状态。"/> : !runs.length ? <Empty title="没有运行记录" text="启动一次 Agent 任务后，运行和审批会出现在这里。"/> : runs.slice(0,8).map(run => <a className="list-row" key={run.id} href="#/agent"><div><strong>{run.id}</strong><small>{run.pending_approval?.reason || '打开 Agent 查看执行摘要'}</small></div><Status status={run.status}/></a>)}</Card></div>
    <div className="quick-links">{[{id:'planning',title:'研究规划',text:'问题、实验与任务依赖'},{id:'papers',title:'文献证据',text:'合法全文与原文定位'},{id:'writing',title:'文献写作',text:'段落出处与版本保护'},{id:'tasks',title:'任务成果',text:'真实产物与鉴权下载'}].map(item => <a className="quick-link" key={item.id} href={`#/${item.id}`}><Icon name={item.id}/><div><strong>{item.title}</strong><small>{item.text}</small></div><Icon name="arrow" size={17}/></a>)}</div>
  </>;
}
