import { useEffect, useState } from 'react';
import { useWorkbench } from '../context';
import { api, errorText, post } from '../api';
import type { Data } from '../types';
import { ResultView } from '../components/Results';
import { Badge, Button, Card, Check, Field, Icon, Notice, PageHeading, Tabs } from '../components/ui';
export function McpGuide() {
  const {setMode} = useWorkbench();
  return <div className="two-columns"><Card title="在外部 Agent 中使用 MCP" description="MCP 是另一种执行模式，不启动网页内置 Agent，不需要在这里配置模型 Key。"><ol className="steps"><li><span>1</span><div><strong>安装并启动 PaperFlow MCP</strong><pre className="code-block">python -m paperflow run</pre><p>这是 stdio 服务命令，由你的外部客户端启动和管理。</p></div></li><li><span>2</span><div><strong>在外部客户端配置服务</strong><pre className="code-block">{'{\n  "mcpServers": {\n    "paperflow": {\n      "command": "python",\n      "args": ["-m", "paperflow", "run"]\n    }\n  }\n}'}</pre></div></li><li><span>3</span><div><strong>查看共享项目与结果</strong><p>网页里的规划、文献和写作项目与业务服务共享。外部写入仍遵守版本保护，工作区需要显式关联。</p></div></li></ol><Button variant="secondary" onClick={() => setMode('mcp')}>切换为外部 MCP 模式</Button></Card><Card title="连接状态边界"><Notice>本网页无法检测或控制外部 harness，因此不会声称“已经连接”。请在你的外部客户端检查真实握手与工具结果。</Notice><h3>保留原有 MCP Apps</h3><p className="muted">支持 MCP Apps 的宿主仍可使用原有单文件工作台和结果收件箱。本网页不嵌套旧 iframe，也不依赖旧页面运行。</p><h3>手动业务始终可用</h3><p className="muted">MCP 模式下可以继续使用规划、文献、选刊和文档页面；内置模型配置与外部客户端配置互不混用。</p><Badge>外部握手：网页不可检测</Badge></Card></div>;
}
export default function Settings() {
  const {tools,capabilities,refresh,mode} = useWorkbench();const [tab,setTab] = useState('model');const [status,setStatus] = useState<Data>();const [provider,setProvider] = useState('openai_compatible');const [base,setBase] = useState('');const [model,setModel] = useState('');const [key,setKey] = useState('');const [remember,setRemember] = useState(false);const [consent,setConsent] = useState(false);const [error,setError] = useState('');const [busy,setBusy] = useState(false);const [tested,setTested] = useState<Data>();
  async function loadStatus() {try{const data = await api('/api/model/status');setStatus(data);setProvider(data.provider || data.config?.provider || 'openai_compatible');setBase(data.base_url || data.config?.base_url || '');setModel(data.model || data.config?.model || '');setConsent(data.consented === true || data.consent === true);}catch(e){setError(errorText(e));}}
  useEffect(() => {void loadStatus();},[]);
  async function save() {setBusy(true);setError('');const apiKey = key;setKey('');try {await post('/api/model/config',{provider,base_url:base,model,api_key:apiKey,remember});await loadStatus();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <>
    <PageHeading eyebrow="YOU OWN THE ENVIRONMENT" title="设置与接入" description="模型协议、材料发送授权与环境能力都明确可见。访问令牌与模型 Key 是两种不同凭证。"/>
    {error && <Notice danger>{error}</Notice>}
    <Tabs active={tab} onChange={setTab} items={[{id:'model',title:'模型与授权'},{id:'environment',title:'能力与环境'},{id:'mcp',title:'外部 MCP 接入'}]}/>
    {tab === 'model' && <div className="two-columns"><Card title="配置独立 Agent 的模型" description="明确选择协议，不静默切换或重发到其他端点。" action={<Badge tone={mode === 'mcp' ? 'neutral' : 'violet'}>{mode === 'mcp' ? 'MCP 模式无需配置' : '独立模式'}</Badge>}><form onSubmit={e => {e.preventDefault();void save();}}>
      <Field label="工具调用协议"><select value={provider} onChange={e => {setProvider(e.target.value);setKey('');setTested(undefined);}}><option value="openai_compatible">OpenAI 兼容 · Chat Completions</option><option value="openai_responses">OpenAI Responses</option><option value="anthropic">Anthropic Messages</option></select></Field>
      <Field label="模型服务端点" hint="使用受信任的模型服务地址；端点变更需要重新授权。"><input type="url" required value={base} onChange={e => {setBase(e.target.value);setKey('');setTested(undefined);}} placeholder="https://你的模型服务/v1"/></Field>
      <Field label="模型名称"><input required value={model} onChange={e => {setModel(e.target.value);setTested(undefined);}} placeholder="服务支持的模型标识" autoComplete="off"/></Field>
      <Field label="API Key" hint="只在受控提交时发送，不进入 localStorage / sessionStorage，不回显。"><input type="password" value={key} onChange={e => setKey(e.target.value)} autoComplete="new-password" spellCheck={false} placeholder="输入模型凭证；保存后立即清空"/></Field>
      <Check label="请求系统密钥环记住凭证（能力以实际状态为准）" checked={remember} onChange={setRemember}/><div className="form-actions"><Button type="submit" disabled={busy || !base || !model}>{busy ? '保存中…' : '保存模型配置'}</Button></div>
    </form></Card><Card title="实际模型状态与材料授权" description="连接测试会产生一次实际模型请求，可能产生费用。"><ResultView data={status}/><div className="authorization"><Check label="允许将本次明确选中的研究材料发送给配置的模型服务" checked={consent} onChange={async next => {setError('');try{await post('/api/model/consent',{consent:next});setConsent(next);}catch(e){setError(errorText(e));}}}/></div><div className="row-actions"><Button variant="secondary" disabled={!consent || busy} onClick={async () => {setBusy(true);setError('');try{setTested(await post('/api/model/test',{consent:true}));await loadStatus();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}>授权并测试连接</Button><Button variant="ghost" onClick={() => void loadStatus()}><Icon name="refresh" size={16}/>刷新状态</Button></div>{tested && <ResultView data={tested}/>}<Notice>未配置模型也能手动使用不依赖模型的业务功能。预算与联网 / 写入权限在每次 Agent 任务中另行确认。</Notice></Card></div>}
    {tab === 'environment' && <><Card title="环境能力目录" description="来自实际后端注册表；不可用能力显示原因。" action={<Button variant="secondary" onClick={() => void refresh()}>重新检测</Button>}><div className="capability-list">{tools.map(tool => <div className="capability-row" key={tool.name}><span className={`capability-dot ${tool.available ? 'yes' : ''}`}/><div><strong>{tool.name}</strong><p>{tool.description}</p>{!tool.available && <small className="error-text">{tool.unavailable_reason || '当前环境不可用'}</small>}</div><div>{tool.network && <Badge>联网</Badge>}{tool.mutates && <Badge>写入</Badge>}{tool.desktop && <Badge>桌面</Badge>}<Badge tone={tool.available ? 'green' : 'neutral'}>{tool.available ? '可用' : '不可用'}</Badge></div></div>)}</div></Card><Card title="后端环境详情"><ResultView data={{...capabilities,tools:undefined}}/></Card></>}
    {tab === 'mcp' && <McpGuide/>}
  </>;
}
