import { useCallback, useEffect, useState } from 'react';
import { useWorkbench } from '../context';
import { api, errorText, records } from '../api';
import type { Artifact, Data } from '../types';
import { ActionResult, ResultView } from '../components/Results';
import { ArtifactProvenance } from '../components/ArtifactProvenance';
import { ArtifactLink, Badge, Button, Card, Empty, Icon, Loading, Notice, PageHeading, Status, Tabs } from '../components/ui';
export default function Tasks() {
  const {workspace,results,execute,link} = useWorkbench();const [tab,setTab] = useState('artifacts');const [artifacts,setArtifacts] = useState<Artifact[]>([]);const [assets,setAssets] = useState<Data[]>([]);const [runs,setRuns] = useState<Data[]>([]);const [tasks,setTasks] = useState<Data[]>([]);const [oldPapers,setOldPapers] = useState<Data[]>([]);const [error,setError] = useState('');const [loading,setLoading] = useState(false);
  const refresh = useCallback(async () => {setLoading(true);setError('');const suffix = workspace ? '?workspace_id=' + encodeURIComponent(workspace.id) : '';const responses = await Promise.allSettled([api('/api/workbench/artifacts' + suffix),api('/api/workbench/assets' + suffix),api('/api/agent/sessions' + suffix)]);if(responses[0].status === 'fulfilled')setArtifacts(records(responses[0].value) as Artifact[]);if(responses[1].status === 'fulfilled')setAssets(records(responses[1].value,'assets'));if(responses[2].status === 'fulfilled'){const sessions = records(responses[2].value);const details = await Promise.allSettled(sessions.slice(0,20).map(session => api(`/api/agent/sessions/${encodeURIComponent(session.id)}`)));setRuns(details.flatMap(item => item.status === 'fulfilled' ? item.value.runs || [] : []));}setError(responses.filter((item):item is PromiseRejectedResult => item.status === 'rejected').map(item => errorText(item.reason)).join(' '));setLoading(false);},[workspace?.id]);
  useEffect(() => {void refresh();},[refresh]);
  async function planningTasks() {setError('');try {const data = await Promise.all((workspace?.links || []).filter(item => item.kind === 'planning').map(item => execute('planning_get',{project_id:item.target_id})));setTasks(data.flatMap(item => ((item.snapshot || item).plan?.tasks || []).map((task:Data) => ({...task,project_id:(item.snapshot || item).project_id}))));}catch(e){setError(errorText(e));}}
  return <>
    <PageHeading eyebrow="ACTUAL WORK, ACTUAL ARTIFACTS" title="任务与成果" description="跨模块查看实际运行、审批、来源与文件。产物通过不透明标识鉴权下载，不提供任意本地路径。" action={<Button variant="secondary" onClick={() => void refresh()}><Icon name="refresh" size={17}/>刷新真实记录</Button>}/>
    {error && <Notice danger>{error}</Notice>}
    <Tabs active={tab} onChange={setTab} items={[{id:'artifacts',title:'成果文件'},{id:'runs',title:'Agent 运行与审批'},{id:'planning',title:'规划任务'},{id:'assets',title:'研究材料'},{id:'activity',title:'本次操作记录'}]}/>
    {loading && <Loading/>}
    {tab === 'artifacts' && <Card title="工作区产物" action={<Badge>{artifacts.length} 个</Badge>}>{!artifacts.length ? <Empty title="尚无真实成果文件" text="导出规划、写作 DOCX 或规范化副本后，会在这里显示。"/> : <div className="artifact-grid">{artifacts.map(artifact => <div key={artifact.artifact_id || artifact.id}><ArtifactLink artifact={artifact}/><ArtifactProvenance artifact={artifact}/></div>)}</div>}</Card>}
    {tab === 'runs' && <Card title="运行状态 / 待审批">{!runs.length ? <Empty title="当前工作区没有 Agent 运行"/> : runs.map(run => <div className="run-list-card" key={run.id}><div className="list-row"><div><strong>{run.id}</strong><small>{run.pending_approval?.reason || '打开会话查看执行摘要'}</small></div><Status status={run.status}/><a className="button secondary" href="#/agent">打开会话</a></div>{run.error && <Notice danger>{typeof run.error === 'string' ? run.error : run.error.message || '执行失败，请在会话中查看原因'}</Notice>}<ResultView data={run.usage || {usage:'实际用量未提供'}}/></div>)}</Card>}
    {tab === 'planning' && <Card title="科研规划任务" action={<Button variant="secondary" onClick={() => void planningTasks()}>读取关联规划</Button>}>{!tasks.length ? <Empty title="尚未读取任务" text="从当前工作区已关联的规划中读取任务。"/> : tasks.map(task => <div className="task-row" key={task.id}><Status status={task.status}/><div><strong>{task.text}</strong><small>{task.completion_condition}</small>{task.blocked_reason && <small className="error-text">受阻：{task.blocked_reason}</small>}<small>项目 {task.project_id} · 前置 {task.depends_on?.join('、') || '无'}</small></div></div>)}</Card>}
    {tab === 'assets' && <><Card title="已上传的受管材料"><ResultView data={assets}/>{!assets.length && <Empty title="尚未上传材料" text="在文献或文档页面上传需要处理的文件。"/>}</Card><Card title="发现并关联已有文献" description="只发现真实元数据，不自动发送模型或打开全文。" action={<Button variant="secondary" onClick={async () => {try{setOldPapers(records(await execute('papers_list',{limit:50,offset:0,discover:true})));}catch(e){setError(errorText(e));}}}>发现本地文献</Button>}>{oldPapers.map(paper => <div className="list-row" key={paper.paper_id}><div><strong>{paper.title || paper.paper_id}</strong><small>{paper.paper_id}</small></div><Button variant="secondary" disabled={!workspace || workspace.links?.some(item => item.target_id === paper.paper_id)} onClick={async () => {try{await link('paper',paper.paper_id);}catch(e){setError(errorText(e));}}}>关联文献</Button></div>)}</Card></>}
    {tab === 'activity' && <Card title="当前页面会话的实际操作" description="这是本次浏览器会话的响应记录，不替代后端持久化审计日志。">{!results.length ? <Empty title="尚无业务操作"/> : results.map((item,index) => <div key={index}><div className="activity-heading"><strong>{item.action}</strong><small>{new Date(item.at).toLocaleString('zh-CN')}</small></div><ActionResult data={item.data} title="真实服务响应"/></div>)}</Card>}
  </>;
}
