import { useCallback, useEffect, useState } from 'react';
import { useWorkbench } from '../context';
import { errorText, records } from '../api';
import type { Data } from '../types';
import { initialValue, SchemaEditor, validate } from '../components/SchemaForm';
import { ActionResult, ResultView } from '../components/Results';
import { ToolPanel } from '../components/ToolPanel';
import { Badge, Button, Card, Empty, Field, Icon, Notice, PageHeading, Tabs } from '../components/ui';
export default function Writing() {
  const {tools,execute,workspace,link,askAgent} = useWorkbench(); const [projects,setProjects] = useState<Data[]>([]);const [id,setId] = useState('');const [snapshot,setSnapshot] = useState<Data>();const [materials,setMaterials] = useState<Data>();
  const [tab,setTab] = useState('draft');const [draft,setDraft] = useState<Data>();const [assessments,setAssessments] = useState<Data>({});const [error,setError] = useState('');const [busy,setBusy] = useState(false);const [note,setNote] = useState('更新文献支持草稿');
  const [loop,setLoop] = useState<Data>();const [review,setReview] = useState<Data>();const [historical,setHistorical] = useState<Data>();const [historyRevision,setHistoryRevision] = useState(1);
  const draftTool = tools.find(t => t.name === 'writing_draft');const draftSchema = draftTool?.input_schema.properties?.draft;
  const list = useCallback(async () => {try {setProjects(records(await execute('writing_list',{limit:30,offset:0})));}catch(e){setError(errorText(e));}},[execute]);
  useEffect(() => {if(tools.some(t => t.name === 'writing_list')) void list();},[tools,list]);
  useEffect(() => {setId('');setSnapshot(undefined);setDraft(undefined);setLoop(undefined);setMaterials(undefined);},[workspace?.id]);
  async function load(target = id) {if(!target)return;setError('');try {const data = await execute('writing_get',{project_id:target,evidence_offset:0,evidence_limit:40});const snap = data.snapshot || data.project || data;setId(target);setSnapshot(snap);setMaterials(data);setDraft(structuredClone(snap.draft || {title:snap.profile?.title || '',language:snap.profile?.language || 'zh',outline:[],sections:[]}));setAssessments(Object.fromEntries((snap.assessments || []).map((item:Data) => [item.paper_id,{paper_id:item.paper_id,metadata_sha256:item.metadata_sha256,relevance:item.relevance,reason:item.reason,question_ids:item.question_ids,basis:item.basis,limitations:item.limitations,evidence_ids:item.evidence_ids}])));}catch(e){setError(errorText(e));}}
  async function created(data:Data) {const snap = data.snapshot || data; if(snap.project_id){await link('writing',snap.project_id).catch(e => setError(errorText(e)));await list();await load(snap.project_id);setTab('candidates');}}
  async function saveDraft() {if(!draftTool || !draftSchema || !draft || !snapshot)return;const errors = validate(draftSchema,draft,draftTool.input_schema);if(errors.length){setError(errors.slice(0,8).join('；'));return;}setBusy(true);setError('');try{await execute('writing_draft',{project_id:id,draft,expected_revision:snapshot.revision,change_note:note});await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function saveAssessments() {if(!snapshot)return;setBusy(true);setError('');try{const items = Object.values(assessments);await execute('writing_assess',{project_id:id,expected_revision:snapshot.revision,assessments:items,selected_paper_ids:items.filter((a:any) => ['core','background'].includes(a.relevance)).map((a:any) => a.paper_id)});await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function getLoop() {if(!id)return;try{const data = await execute('loop_get',{project_id:id});setLoop(data.loop || data); }catch(e){setError(errorText(e));}}
  const matrix = materials?.evidence_matrix || materials?.matrix || materials?.evidence || [];
  const dual = {project_id:id,expected_loop_revision:loop?.loop_revision ?? loop?.revision ?? 0,expected_project_revision:snapshot?.revision};
  return <>
    <PageHeading eyebrow="FROM REAL PAPERS TO YOUR MANUSCRIPT" title="文献支持写作" description="从研究问题出发，多查询找论文，再用正文证据组织稿件。没有本人实验材料时，不把他人结果写成自己的。" action={<Button variant="secondary" onClick={() => askAgent(`请推进文献写作${id ? `项目 ${id}，当前版本 ${snapshot?.revision}` : ''}：检索、判断相关性、合法获取、分页阅读并保存证据支持草稿。实际实验数据缺失时保持占位。`)}><Icon name="agent" size={17}/>交给 Agent 推进</Button>}/>
    {error && <Notice danger>{error}</Notice>}
    <div className="project-toolbar"><Icon name="writing"/><select aria-label="文献写作项目" value={id} onChange={e => void load(e.target.value)}><option value="">选择写作项目</option>{projects.map(project => <option key={project.project_id} value={project.project_id}>{project.title || project.profile?.title || project.project_id} · v{project.revision}</option>)}</select><Button variant="ghost" onClick={() => void list()}><Icon name="refresh" size={16}/>刷新列表</Button>{snapshot && <Badge tone="violet">版本 {snapshot.revision}</Badge>}</div>
    <Tabs active={tab} onChange={setTab} items={[{id:'draft',title:'大纲与草稿'},{id:'create',title:'主题与检索计划'},{id:'candidates',title:'候选筛选'},{id:'evidence',title:'正文证据'},{id:'loop',title:'自适应补读'},{id:'history',title:'修订与导出'}]}/>
    {tab === 'create' && <div className="two-columns"><ToolPanel name="writing_prepare" title="准备研究主题" description="返回实际输入标识与研究画像契约，不自动编造实验。"/><ToolPanel name="writing_create" title="创建文献写作项目" description="填写核心问题、实际材料和最多六条检索式；创建本身不会联网。" onResult={data => void created(data)}/></div>}
    {!snapshot && tab !== 'create' && <Empty title="还没有选中的写作项目" text="新建一个课题，或者从顶部选择已关联的项目。" action={<Button onClick={() => setTab('create')}><Icon name="plus" size={16}/>创建写作项目</Button>}/>}
    {snapshot && tab === 'candidates' && <>
      <ToolPanel name="writing_search" title="执行项目多查询" description="检索会生成新版本；来源失败不等于没有文献。" preset={{project_id:id,expected_revision:snapshot.revision}} onResult={() => void load()}/>
      <Card title="真实候选与相关性筛选" description="服务绑定真实元数据指纹。摘要判断不能冒充正文判断。" action={<Badge>{snapshot.candidates?.length || 0} 篇</Badge>}>
        <ResultView data={snapshot.search_statuses}/>
        {!snapshot.candidates?.length ? <Empty title="尚无候选" text="先执行项目检索，或让 Agent 规划多查询。"/> : snapshot.candidates.map((candidate:Data) => {
          const item = assessments[candidate.paper_id]; const change = (patch:Data) => setAssessments({...assessments,[candidate.paper_id]:{paper_id:candidate.paper_id,metadata_sha256:candidate.metadata_sha256,relevance:'marginal',reason:'',question_ids:snapshot.profile?.sub_questions?.map((q:Data) => q.id) || [],basis:'abstract',limitations:[],evidence_ids:[],...item,...patch}});
          return <article className="candidate-card" key={candidate.paper_id}><div className="candidate-heading"><div><Badge>{candidate.paper?.source_id}</Badge><h3>{candidate.paper?.title || candidate.paper_id}</h3><p>{candidate.paper?.abstract || '来源未提供摘要'}</p></div><select aria-label={`相关性 ${candidate.paper?.title || candidate.paper_id}`} value={item?.relevance || ''} onChange={e => change({relevance:e.target.value})}><option value="">尚未判断</option><option value="core">核心 · 选入</option><option value="background">背景 · 选入</option><option value="marginal">边缘</option><option value="irrelevant">不相关</option></select></div>{item && <div className="candidate-form"><Field label="筛选理由"><textarea rows={2} value={item.reason} onChange={e => change({reason:e.target.value})}/></Field><Field label="判断依据"><select value={item.basis} onChange={e => change({basis:e.target.value})}><option value="metadata">元数据</option><option value="abstract">摘要</option><option value="fulltext">实际正文证据</option></select></Field><Field label="关联研究问题"><select multiple value={item.question_ids} onChange={e => change({question_ids:Array.from(e.target.selectedOptions).map(o => o.value)})}>{snapshot.profile?.sub_questions?.map((q:Data) => <option key={q.id} value={q.id}>{q.id} · {q.question}</option>)}</select></Field>{item.basis === 'fulltext' && <Field label="正文引用标识"><select multiple value={item.evidence_ids} onChange={e => change({evidence_ids:Array.from(e.target.selectedOptions).map(o => o.value)})}>{records(matrix).map((e:Data) => <option key={e.citation_id} value={e.citation_id}>{e.citation_id} · {e.text || e.claim_text}</option>)}</select></Field>}</div>}</article>;
        })}
        {!!snapshot.candidates?.length && <div className="form-actions"><Button disabled={busy || !Object.keys(assessments).length} onClick={() => void saveAssessments()}>{busy ? '保存中…' : '保存筛选与选中文献'}</Button></div>}
      </Card>
    </>}
    {snapshot && tab === 'draft' && <>
      <Notice>文献归纳 / 推断段落必须关联实际正文引用；用户材料段落必须关联实际材料标识。没有证据或实验数据时，请选择“缺失材料占位”。</Notice>
      <div className="draft-layout"><Card title="大纲与段落编辑" description="标题级别、论述类型、来源归属与引用同时保存。" action={<Badge>v{snapshot.revision}</Badge>}>{draftSchema && draftTool && draft ? <SchemaEditor schema={draftSchema} root={draftTool.input_schema} value={draft} onChange={setDraft}/> : <Empty title="服务没有返回草稿编辑契约"/>}<div className="save-bar"><Field label="修订说明"><input value={note} onChange={e => setNote(e.target.value)}/></Field><Button disabled={busy || !note.trim()} onClick={() => void saveDraft()}>保存新草稿版本</Button><Button variant="secondary" onClick={() => void load()}>读取最新版本</Button></div></Card><Card title="可用引用与用户材料" description="只复制真实证据标识，不手造引用或 DOI"><ResultView data={matrix}/><ResultView data={snapshot.profile?.own_materials}/></Card></div>
    </>}
    {snapshot && tab === 'evidence' && <div className="two-columns"><ToolPanel name="writing_materials" title="分页读取写作证据" description="单批材料不是全部证据。按偏移继续读取，检查实际覆盖与缺口。" preset={{project_id:id}} onResult={setMaterials}/><Card title="证据矩阵与缺口"><ResultView data={materials}/></Card></div>}
    {snapshot && tab === 'loop' && <>
      <Card title="补读状态与预算" description="GUI 模型预算可以为零；每次操作同时保护项目版本与补读版本。" action={<Button variant="secondary" onClick={() => void getLoop()}><Icon name="refresh" size={16}/>读取补读状态</Button>}>{loop ? <ResultView data={loop}/> : <Empty title="尚未读取补读状态" text="读取现有阶段、实际消耗与待执行动作后再操作。"/>}</Card>
      {loop && <div className="two-columns"><ToolPanel name="loop_control" title="控制补读与预算" preset={dual} onResult={data => {setLoop(data.loop || data);void load();}}/><ToolPanel name="loop_prepare_review" title="准备证据评审上下文" preset={{project_id:id}} onResult={setReview}/>{review && <ToolPanel name="loop_submit_review" title="提交有出处的评审" preset={{...dual,context_fingerprint:review.context_fingerprint || review.context?.context_fingerprint}} onResult={() => void getLoop()}/>}<ToolPanel name="loop_step" title="执行一个已规划动作" description="使用状态返回的实际动作标识；不会自动重复副作用。" preset={dual} onResult={() => {void getLoop();void load();}}/><ToolPanel name="loop_feedback" title="提交阶段解读 / 修订反馈" preset={dual} onResult={() => {void getLoop();void load();}}/></div>}
    </>}
    {snapshot && tab === 'history' && <div className="two-columns"><ToolPanel name="writing_export" title="导出有出处的 DOCX" description="独立草稿包含真实参考信息与证据定位附录；不是已完成实验的论文。" preset={{project_id:id}}/><Card title="历史修订对照"><div className="inline-form"><Field label="历史版本"><input type="number" min={1} max={snapshot.revision} value={historyRevision} onChange={e => setHistoryRevision(Number(e.target.value))}/></Field><Button variant="secondary" onClick={async () => {try{setHistorical(await execute('writing_get',{project_id:id,revision:historyRevision}));}catch(e){setError(errorText(e));}}}>读取历史版本</Button></div>{historical && <><div className="revision-diff"><div><h3>历史 v{historyRevision}</h3><ResultView data={(historical.snapshot || historical).draft}/></div><div><h3>当前 v{snapshot.revision}</h3><ResultView data={snapshot.draft}/></div></div><ActionResult data={historical} title="历史版本完整响应"/></>}</Card></div>}
  </>;
}
