import { Component, lazy, Suspense, useEffect, useState, type ReactNode } from 'react';
import { hasToken, initializeToken } from './api';
import { useWorkbench, WorkbenchProvider } from './context';
import { Badge, Button, Empty, Icon, Loading, Notice, Tabs } from './components/ui';
import { ResultView } from './components/Results';
const Home = lazy(() => import('./pages/Home')); const Agent = lazy(() => import('./pages/Agent'));const Planning = lazy(() => import('./pages/Planning'));const Papers = lazy(() => import('./pages/Papers'));const Writing = lazy(() => import('./pages/Writing'));const Journals = lazy(() => import('./pages/Journals'));const Submission = lazy(() => import('./pages/Submission'));const Documents = lazy(() => import('./pages/Documents'));const Tasks = lazy(() => import('./pages/Tasks'));const Settings = lazy(() => import('./pages/Settings'));
const nav = [
  {id:'home',title:'项目首页',icon:'home',group:'工作空间'}, {id:'agent',title:'Agent 工作区',icon:'agent',group:'工作空间'},
  {id:'planning',title:'科研规划',icon:'planning',group:'研究与写作'},{id:'papers',title:'文献库',icon:'papers',group:'研究与写作'},{id:'writing',title:'文献写作',icon:'writing',group:'研究与写作'},
  {id:'journals',title:'选刊与数据源',icon:'journals',group:'投稿与交付'},{id:'submission',title:'投稿与参考文献',icon:'submission',group:'投稿与交付'},{id:'documents',title:'文档与格式',icon:'documents',group:'投稿与交付'},{id:'tasks',title:'任务与成果',icon:'tasks',group:'投稿与交付'},
  {id:'settings',title:'设置与 MCP 接入',icon:'settings',group:'环境'}
];
const pages: Record<string,React.LazyExoticComponent<React.ComponentType>> = {home:Home,agent:Agent,planning:Planning,papers:Papers,writing:Writing,journals:Journals,submission:Submission,documents:Documents,tasks:Tasks,settings:Settings};
function useRoute() {const route = () => location.hash.replace(/^#\/?/,'').split('?')[0] || 'home';const [value,setValue] = useState(route);useEffect(() => {const changed = () => setValue(route());window.addEventListener('hashchange',changed);return () => window.removeEventListener('hashchange',changed);},[]);return value;}
function EvidenceDock() {
  const {results,askAgent,mode,workspace} = useWorkbench();const [tab,setTab] = useState('agent');const [prompt,setPrompt] = useState('');
  return <aside className="evidence-dock"><div className="dock-heading"><Icon name="agent"/><strong>研究助手</strong><span className="online-indicator" aria-label="本地界面"/></div><Tabs active={tab} onChange={setTab} items={[{id:'agent',title:'Agent'},{id:'evidence',title:'证据 / 结果'}]}/>{tab === 'agent' ? <div className="dock-content"><div className="dock-symbol"><Icon name="agent" size={29}/></div><h3>下一步，清晰可控</h3><p>{mode === 'standalone' ? '带上当前工作区的目标，在完整会话中查看执行、审批和预算。' : '外部 MCP 模式由你的客户端管理执行。这里不会调用内置模型。'}</p><div className="dock-scope"><small>当前作用域</small><strong>{workspace?.title || '尚未选择工作区'}</strong><Badge>{workspace?.links?.length || 0} 个关联项目</Badge></div><textarea aria-label="侧栏 Agent 目标" rows={4} value={prompt} onChange={e => setPrompt(e.target.value)} placeholder="描述你希望推进的目标…"/><Button disabled={!prompt.trim() || !workspace || mode === 'mcp'} onClick={() => askAgent(prompt)}>打开执行会话<Icon name="arrow" size={16}/></Button><Notice>材料外发、联网和写入需要明确授权。模型未配置时仍能手动操作。</Notice><a className="quiet-link" href="#/settings">模型设置与接入<Icon name="chevron" size={14}/></a></div> : <div className="dock-content dock-results">{!results.length ? <Empty title="尚无真实结果" text="业务操作和 Agent 实际工具结果会出现在这里。"/> : results.slice(0,5).map((item,i) => <details className="dock-result" key={i} open={i === 0}><summary>{item.action}<small>{new Date(item.at).toLocaleTimeString('zh-CN')}</small></summary><ResultView data={item.data}/></details>)}<a className="button secondary" href="#/tasks">查看任务与成果</a></div>}</aside>;
}
function Shell() {
  const {workspaces,workspace,selectWorkspace,mode,setMode,error,refresh,loading} = useWorkbench();const route = useRoute();const [mobileNav,setMobileNav] = useState(false);const [dock,setDock] = useState(true);const [search,setSearch] = useState('');const fullAgent = route === 'agent';const Page = pages[route];
  useEffect(() => {setMobileNav(false);window.scrollTo?.(0,0);},[route]);
  return <div className={`app-shell ${fullAgent ? 'agent-full' : ''} ${!dock ? 'dock-hidden' : ''}`}>
    <aside className={`main-sidebar ${mobileNav ? 'mobile-open' : ''}`}><a href="#/home" className="brand"><span className="brand-mark"><Icon name="papers" size={25}/></span><div><strong>PaperFlow</strong><small>科研工作台</small></div></a><nav aria-label="主导航">{Array.from(new Set(nav.map(item => item.group))).map(group => <div className="nav-group" key={group}><span>{group}</span>{nav.filter(item => item.group === group).map(item => <a href={`#/${item.id}`} key={item.id} aria-label={item.title} aria-current={route === item.id ? 'page' : undefined} className={route === item.id ? 'active' : ''}><Icon name={item.icon} size={19}/><span>{item.title}</span>{item.id === 'agent' && <Badge>AI</Badge>}</a>)}</div>)}</nav><div className="sidebar-footer"><span className="local-dot"/><div><strong>本地优先</strong><small>材料访问与执行受控</small></div><Icon name="shield" size={18}/></div></aside>
    <header className="topbar"><div className="topbar-left"><button className="icon-button mobile-nav-toggle" aria-label="展开主导航" onClick={() => setMobileNav(!mobileNav)}><Icon name="menu"/></button><span className="breadcrumb">工作台<Icon name="chevron" size={14}/><strong>{nav.find(item => item.id === route)?.title || '页面不存在'}</strong></span></div><div className="topbar-controls"><div className="workspace-switch"><Icon name="folder" size={16}/><select aria-label="当前工作区" value={workspace?.id || ''} onChange={e => selectWorkspace(e.target.value)}><option value="">{workspaces.length ? '选择工作区' : '尚无工作区'}</option>{workspaces.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div><select aria-label="执行模式" className="mode-select" value={mode} onChange={e => setMode(e.target.value as typeof mode)}><option value="standalone">独立 Agent</option><option value="mcp">外部 MCP</option></select><div className="navigation-search"><Icon name="search" size={16}/><input aria-label="查找功能" placeholder="查找功能" value={search} onChange={e => setSearch(e.target.value)}/>{search && <div className="search-options">{nav.filter(item => item.title.toLowerCase().includes(search.toLowerCase())).map(item => <a key={item.id} href={`#/${item.id}`} onClick={() => setSearch('')}><Icon name={item.icon} size={17}/>{item.title}</a>)}{!nav.some(item => item.title.toLowerCase().includes(search.toLowerCase())) && <p>没有匹配的功能</p>}</div>}</div>{!fullAgent && <button className="icon-button" aria-label={dock ? '收起研究助手侧栏' : '展开研究助手侧栏'} onClick={() => setDock(!dock)}><Icon name="agent"/></button>}</div></header>
    <main className={`main-content ${fullAgent ? 'main-agent' : ''}`} id="main">{error && <Notice danger>{error}<Button variant="ghost" onClick={() => void refresh()}>重新连接</Button></Notice>}{loading && !Page && <Loading/>}<Suspense fallback={<Loading/>}>{Page ? <Page/> : <Empty title="没有这个页面" text="从左侧选择一个科研模块。" action={<a className="button primary" href="#/home">回到首页</a>}/>}</Suspense>{!fullAgent && <footer className="workbench-footer"><span>PaperFlow · 真实材料，实际结果，可追溯证据</span><span><Icon name="shield" size={13}/>受控本地工作区</span></footer>}</main>
    {dock && !fullAgent && <EvidenceDock/>}{mobileNav && <button className="mobile-scrim" aria-label="关闭导航" onClick={() => setMobileNav(false)}/>}
  </div>;
}
class ErrorBoundary extends Component<{children:ReactNode},{error:boolean}> {
  state = {error:false};static getDerivedStateFromError() {return {error:true};}
  render() {return this.state.error ? <div className="startup-screen"><Notice danger>界面遇到错误。已停止当前页面渲染，不会自动重发业务操作。</Notice><Button onClick={() => location.reload()}>重新加载界面</Button></div> : this.props.children;}
}
export default function App() {
  const [authenticated,setAuthenticated] = useState(() => {initializeToken();return hasToken();});
  useEffect(() => {const expired = () => setAuthenticated(false);window.addEventListener('paperflow:unauthorized',expired);return () => window.removeEventListener('paperflow:unauthorized',expired);},[]);
  if(!authenticated)return <div className="startup-screen"><div className="startup-card"><span className="brand-mark"><Icon name="papers" size={30}/></span><Badge tone="violet">PaperFlow · 本地科研工作台</Badge><h1>请使用启动链接进入</h1><p>访问令牌缺失或已过期。从运行 PaperFlow 的终端重新打开带令牌的启动链接。</p><Notice>启动链接只用于本地网页认证，不是模型 API Key。认证后令牌会从地址栏移除。</Notice><div className="code-block">python -m paperflow web</div><Button variant="secondary" onClick={() => location.reload()}>已重新启动，刷新页面</Button></div></div>;
  return <ErrorBoundary><WorkbenchProvider><Shell/></WorkbenchProvider></ErrorBoundary>;
}
